version: '2'
services: 
  vscovid-crawler:
    build: .
    volumes: 
      - .:/home/ubuntu/vscovid-crawler
    ports:
      - "8080:80"
    entrypoint: /home/ubuntu/vscovid-crawler/docker/entrypoint.sh