version: 2.1
jobs:
  build:
    docker: 
      - image: ubuntu:18.04
    steps:
      - checkout # check out the code in the project directory
      - run:
        name: Install Ubuntu Packages
        command: apt-get update && apt-get install -y make wget jq redis-tools
      - run: make test
        name: Run `make test`
        command: make test

